# Generated by Django 2.0.13 on 2019-04-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cerveja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estabelecimento', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('volume', models.FloatField()),
            ],
        ),
    ]
