# Generated by Django 2.0.13 on 2019-04-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cerveja',
            old_name='volume',
            new_name='valor',
        ),
    ]
